version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform: x64
clone_folder: "c:\\UnicornEngine"
environment:
  VULKAN_SDK: "c:\\VulkanSDK\\1.42.1.0\\"


init:
  - curl -fsS -o vulkan-installer.exe https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.0.42.1/windows/VulkanSDK-1.0.42.1-Installer.exe
  - vulkan-installer.exe /S
  - rm -f vulkan-installer.exe

install:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: "build\\Godlike.sln"
  parallel: true
  verbosity: minimal

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - ctest -VV -C %CONFIGURATION%

notifications:
- provider: Email
  to:
    - nikita.krupitskas@gmail.com
    - odintsoff@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
